name: 🔨 Forge - Early Stage Hunt Idea
description: A collaborative workspace for developing and refining early-stage threat hunting ideas before they become full HEARTH submissions
labels: ['forge', 'idea', 'early-stage', 'threat-hunting']

body:
  - type: markdown
    attributes:
      value: |
        # Welcome to the HEARTH Forge! 🔨
        This space is for developing early-stage threat hunting ideas. Unlike full HEARTH submissions,
        Forge ideas don't need to be fully tested or documented - they're a starting point for
        collaboration and refinement.
        
        ⚠️ For completed, tested hunt methodologies, please use the HEARTH Hunt Submission Form instead.

  - type: input
    id: submitter
    attributes:
      label: "Forge Contributor (HEARTH Apprentice)"
      description: "Your name or handle for community recognition"
      placeholder: "e.g., @username"
    validations:
      required: true

  - type: input
    id: idea_name 
    attributes:
      label: "Working Title"
      description: "A name for your hunting idea (can be changed later)"
      placeholder: "e.g., Suspicious Service Creation Pattern Analysis"
    validations:
      required: true

  - type: dropdown
    id: development_stage
    attributes:
      label: "Development Stage"
      description: "Where is this idea in its development?"
      options:
        - "Initial Concept - Just a thought or observation"
        - "Early Research - Started investigating feasibility"
        - "Partial Testing - Some preliminary validation"
        - "Ready for Feedback - Need community input"
    validations:
      required: true

  - type: dropdown
    id: hunt_type
    attributes:
      label: "Potential Hunt Type"
      description: "Which PEAK hunt type might this develop into?"
      options:
        - "Flames (Hypothesis-Driven) - Testing specific attack theories"
        - "Embers (Baseline) - Understanding normal behavior"
        - "Alchemy (Model-Assisted) - Using data science approaches"
        - "Not Sure Yet - Need community input"
    validations:
      required: true

  - type: textarea
    id: concept_hypothesis
    attributes:
      label: "Initial Concept"
      description: "Share your hunting idea or observation - it doesn't need to be fully formed yet!"
      placeholder: |
        Example formats:
        - I noticed [observation] and wonder if...
        - What if we looked at [data] to find...
        - Could [technique] be used to detect...
    validations:
      required: true

  - type: textarea
    id: why_interesting
    attributes:
      label: "Potential Value"
      description: "Why might this be worth exploring? What sparked your interest?"
      placeholder: |
        Consider:
        - What threats could this detect?
        - Why current approaches might miss this?
        - Any real-world incidents that inspired this?
    validations:
      required: true

  - type: checkboxes
    id: development_needs
    attributes:
      label: "Development Needs"
      description: "What kind of help do you need to develop this idea?"
      options:
        - label: "Technical feasibility feedback"
        - label: "Data source suggestions"
        - label: "Detection logic refinement"
        - label: "Use case validation"
        - label: "Tool/platform recommendations"
        - label: "Similar technique examples"
        - label: "Data science/ML guidance"
        - label: "Performance optimization ideas"

  - type: textarea
    id: current_challenges
    attributes:
      label: "Current Challenges"
      description: "What obstacles or questions are you facing?"
      placeholder: |
        Examples:
        - Not sure if the data contains what we need
        - Performance concerns with large datasets
        - Need help with detection logic
        - Unsure about false positive rates

  - type: textarea
    id: collaboration_needs
    attributes:
      label: "Collaboration Needs"
      description: "How can the community help develop this idea?"
      placeholder: |
        What specific input would help move this forward?
        - Technical expertise needed
        - Testing environments required
        - Validation scenarios desired

  - type: textarea
    id: resources_references
    attributes:
      label: "Resources & References"
      description: "Any relevant articles, tools, or research that might help develop this idea"
      placeholder: |
        - Related blog posts
        - Similar techniques
        - Relevant attack documentation
        - Useful tools or scripts

  - type: markdown
    attributes:
      value: |
        ## When to Graduate to Full HEARTH Submission
        Your Forge idea may be ready for a full HEARTH submission when:
        - You have a clear, testable hypothesis
        - The detection methodology is documented and repeatable
        - You've validated the approach in at least one environment
        - You can provide concrete examples and use cases
        - The technique provides actionable results

        When ready, submit your matured idea through the HEARTH Hunt Submission Form!
