name: "THOR Submission Form"
about: "Provide details about the hunt idea for submission."
title: "[H/B/M][Unique Hunt Number]"
body:
  - type: markdown
    attributes:
      value: Provide a brief description of the adversary’s potential actions, explaining what behavior or activity you suspect.

  - type: input
    attributes:
      label: Hunt
      description: [H/B/M][Number]
      placeholder: e.g., H001
      required: true

  - type: textarea
    attributes:
      label: Hypothesis
      description: "Describe what the adversary might be trying to accomplish, e.g., accessing sensitive files, escalating privileges, etc."
      placeholder: Brief description of the hypothesis
      required: true

  - type: input
    attributes:
      label: Tactic
      description: "Relevant MITRE ATT&CK tactic (e.g., Persistence, Defense Evasion)"
      placeholder: e.g., Persistence
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: "Notes on limitations, assumptions, or details about the systems in question."
      placeholder: Additional notes
      required: true

  - type: input
    attributes:
      label: Tags
      description: "Relevant tags like #[Tactic] #[Keywords related to the activity]"
      placeholder: "#Persistence #FileAccess"
      required: true

  - type: input
    attributes:
      label: Submitter
      description: "Submitter’s name or handle"
      placeholder: "e.g., @username"
      required: true

  - type: markdown
    attributes:
      value: |
        ## Why
        Explain why this hypothesis is important. What risks does this behavior pose to the organization? Discuss potential consequences if the hypothesis is proven true and mention if this hypothesis connects to larger campaigns or targets high-value assets.

  - type: textarea
    attributes:
      label: Why
      description: "Explain the importance of this hypothesis and its potential consequences."
      placeholder: Provide details
      required: true

  - type: markdown
    attributes:
      value: |
        ## Next Steps
        Outline the next steps required to complete the investigation or further develop this hypothesis. Mention any additional data sources, tools, or queries that could help validate or refine this hypothesis.

  - type: textarea
    attributes:
      label: Next Steps
      description: "Outline the next steps required to develop or investigate this hypothesis."
      placeholder: Provide details
      required: true

  - type: markdown
    attributes:
      value: |
        ## References

  - type: textarea
    attributes:
      label: References
      description: "Include any relevant links or references that support the hypothesis."
      placeholder: Provide references
      required: true

  - type: dropdown
    attributes:
      label: Which type of hunt idea is this?
      options:
        - H (Hypothesis-Driven): Based on assumptions about adversary behavior or specific activities.
        - B (Baseline): Focused on identifying deviations from typical behavior."
        - M (Model-Assisted): Hunts driven by models like anomaly detection or machine learning.
