name: "THOR Submission Form"
about: "Provide details about the hunt idea for submission."
title: "[H/B/M][Unique Hunt Number]"
body:
  - type: markdown
    attributes:
      value: Provide a brief description of the adversary’s potential actions, explaining what behavior or activity you suspect.
