name: HEARTH Hunt Submission Form
description: Template to submit a new threat hunting idea to the HEARTH community
labels: ['hunt', 'submission', 'threat-hunting']

body:
- type: dropdown
  id: hunt_type
  attributes:
    label: Hunt Type 🔥
    options:
      - Flames (Hypothesis-Driven): Based on assumptions about adversary behavior or specific activities.
      - Embers (Baseline): Focused on identifying deviations from typical behavior.
      - Alchemy (Model-Assisted): Hunts driven by models like anomaly detection or machine learning.

- type: input
  id: submitter
  attributes:
    label: HEARTH Crafter
    description: 'Your name or handle for community recognition'
    placeholder: 'e.g., @username'

- type: textarea
  id: hypothesis
  attributes:
    label: Hunt Idea / Hypothesis
    description: 'Describe the threat activity or behavior you aim to detect. For Flames, describe what the adversary might be doing. For Embers, describe what normal behavior looks like. For Alchemy, describe the patterns you want to detect.'
    placeholder: 'Brief description of your hunt idea'

- type: input
  id: tactic
  attributes:
    label: MITRE ATT&CK Tactic
    description: 'Relevant MITRE ATT&CK tactic (e.g., Persistence, Defense Evasion)'
    placeholder: 'e.g., Persistence'

- type: textarea
  id: notes
  attributes:
    label: Implementation Notes
    description: 'Notes on limitations, assumptions, data requirements, or specific system details needed.'
    placeholder: 'Additional implementation details'

- type: input
  id: tags
  attributes:
    label: Search Tags
    description: 'Add relevant tags to help others find your hunt idea: #[Tactic] #[DataSource] #[ThreatActor] #[Technique]'
    placeholder: '#Persistence #WindowsEvents #Scheduled Tasks'

- type: markdown
  attributes:
    value: |
      ## Why Light This Fire? 🔥
      
      - What security risks or threats does this hunt address?
      - What are the potential impacts if malicious activity is found?
      - How does this hunt connect to known threat campaigns or protect critical assets?
      - Why would this hunt be valuable to the community?

- type: textarea
  id: why
  attributes:
    label: Value and Impact
    placeholder: 'Explain why this hunt matters and its potential impact on security'

- type: textarea
  id: references
  attributes:
    label: Knowledge Base
    description: 'Include any supporting references, research, or documentation:'
    placeholder: |
      - MITRE ATT&CK References
      - Related Research Papers
      - Blog Posts or Articles
      - Similar Hunt Techniques
      - Relevant Tools or Frameworks

- type: markdown
  attributes:
    value: |
      > [!IMPORTANT]
      > Upon approval by HEARTH Keepers, your hunt will receive:
      > - Official hunt number (Flames: H####, Embers: B####, or Alchemy: A####)
      > - Community recognition
      > - Integration into the HEARTH repository
