name: THOR Submission Form
description: A template to submit a new hunt idea
title: '[H/B/M][Unique Hunt Number]'
labels: ['hunt', 'submission', 'threat-hunting']

body:
- type: input
  id: hunt_number
  attributes:
    label: Hunt Number
    description: '[H/B/M][Number]'
    placeholder: 'e.g., H001'

- type: textarea
  id: hypothesis
  attributes:
    label: Hypothesis
    description: 'Describe what the adversary might be trying to accomplish, e.g., accessing sensitive files, escalating privileges, etc.'
    placeholder: 'Brief description of the hypothesis'

- type: input
  id: tactic
  attributes:
    label: Tactic
    description: 'Relevant MITRE ATT&CK tactic (e.g., Persistence, Defense Evasion)'
    placeholder: 'e.g., Persistence'


- type: textarea
  id: notes
  attributes:
    label: Notes
    description: 'Notes on limitations, assumptions, or details about the systems in question.'
    placeholder: 'Additional notes'
    

- type: input
  id: tags
  attributes:
    label: Tags
    description: 'Relevant tags like #[Tactic] #[Keywords related to the activity]'
    placeholder: '#Persistence #FileAccess'


- type: input
  id: submitter
  attributes:
    label: Submitter
    description: 'Submitter’s name or handle'
    placeholder: 'e.g., @username'


- type: markdown
  attributes:
    value: |
      Why
      
      - Explain why this hypothesis is important. What risks does this behavior pose to the organization?
      - Discuss potential consequences if the hypothesis is proven true, e.g., what could a successful attack lead to?
      - Mention if this hypothesis connects to larger campaigns or targets high-value assets.

- type: textarea
  id: why
  attributes:
    label: Why
    description: 'Explain the importance of this hypothesis and its potential consequences.'
    placeholder: 'Provide details'


- type: markdown
  attributes:
    value: |
      Next Steps

      - Outline the next steps required to complete the investigation or further develop this hypothesis.
      - Mention any additional data sources, tools, or queries that could help validate or refine this hypothesis.

- type: textarea
  id: next_steps
  attributes:
    label: Next Steps
    description: 'Outline the next steps required to develop or investigate this hypothesis.'
    placeholder: 'Provide details'
    
    
