name: "THOR Submission Form"
about: Provide details about the hunt idea for submission
title: "[H/B/M][Unique Hunt Number]"

body:
- type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
